import React, { useState, useEffect } from 'react';
import type { ExplainPlanResponse } from '../types';
import { 
  Activity, 
  XClose, 
  Copy01, 
  Check, 
  AlertCircle, 
  Terminal, 
  Clock, 
  GitBranch, 
  Database01,
  LayersThree01
} from './Icons';
import { highlightSql } from '../utils/sqlHighlighter';

interface ExplainPlanModalProps {
  isOpen: boolean;
  onClose: () => void;
  plan: ExplainPlanResponse | null;
  isLoading: boolean;
  sql: string;
}

export default function ExplainPlanModal({
  isOpen,
  onClose,
  plan,
  isLoading,
  sql,
}: ExplainPlanModalProps) {
  const [activeTab, setActiveTab] = useState<'visual' | 'raw' | 'sql'>('visual');
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!isOpen) return;
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  const handleCopyRaw = () => {
    if (!plan?.raw_plan?.length) return;
    navigator.clipboard.writeText(plan.raw_plan.join('\n'));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div 
      role="presentation"
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 9999,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'rgba(15, 23, 42, 0.45)',
        backdropFilter: 'blur(4px)',
        padding: '1.25rem',
      }}
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div 
        role="dialog"
        aria-modal="true"
        aria-labelledby="explain-plan-modal-title"
        style={{
          width: '100%',
          maxWidth: '54rem',
          maxHeight: '88vh',
          display: 'flex',
          flexDirection: 'column',
          backgroundColor: 'var(--bg-card)',
          borderRadius: 'var(--radius-md)',
          boxShadow: 'var(--shadow-modal)',
          border: '1px solid var(--cohere-hairline)',
          overflow: 'hidden',
          animation: 'fadeIn 0.15s ease-out',
        }}
      >
        {/* Modal Header */}
        <div 
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            padding: '1rem 1.5rem',
            borderBottom: '1px solid var(--cohere-hairline)',
            backgroundColor: 'var(--cohere-soft-stone)',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
            <div 
              style={{
                width: '2.25rem',
                height: '2.25rem',
                borderRadius: 'var(--radius-sm)',
                backgroundColor: 'var(--bg-card)',
                border: '1px solid var(--cohere-hairline)',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <Activity style={{ width: '1.1rem', height: '1.1rem', color: 'var(--cohere-primary)' }} />
            </div>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                <h3 
                  id="explain-plan-modal-title"
                  style={{
                    fontFamily: 'var(--font-display)',
                    fontSize: '1.05rem',
                    fontWeight: 700,
                    color: 'var(--cohere-ink)',
                    lineHeight: 1.2,
                  }}
                >
                  SQL Execution Plan
                </h3>
                {plan && (
                  <span 
                    style={{
                      fontFamily: 'var(--font-mono)',
                      fontSize: '0.65rem',
                      fontWeight: 700,
                      backgroundColor: 'var(--cohere-primary)',
                      color: 'var(--cohere-canvas)',
                      padding: '2px 8px',
                      borderRadius: 'var(--radius-xs)',
                      textTransform: 'uppercase',
                      letterSpacing: '0.04em',
                    }}
                  >
                    {plan.dialect} • {plan.plan_type}
                  </span>
                )}
              </div>
              <p 
                style={{
                  fontFamily: 'var(--font-body)',
                  fontSize: '0.76rem',
                  color: 'var(--cohere-muted)',
                  marginTop: '2px',
                }}
              >
                Inspect scan strategies, index utilisation, and execution paths generated by the database engine.
              </p>
            </div>
          </div>

          <button
            onClick={onClose}
            className="btn-cohere-pill-outline"
            style={{ 
              padding: '6px', 
              borderRadius: '50%',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              border: 'none',
              backgroundColor: 'transparent'
            }}
            title="Close"
            aria-label="Close Explain Plan modal"
          >
            <XClose style={{ width: '1.1rem', height: '1.1rem', color: 'var(--cohere-slate)' }} />
          </button>
        </div>

        {/* Status / Metric Summary Bar */}
        {plan && !isLoading && (
          <div 
            style={{
              display: 'flex',
              flexWrap: 'wrap',
              alignItems: 'center',
              justifyContent: 'space-between',
              gap: '0.75rem',
              padding: '0.75rem 1.5rem',
              backgroundColor: 'var(--cohere-soft-stone)',
              borderBottom: '1px solid var(--cohere-hairline)',
            }}
          >
            {/* Strategy Badges */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', flexWrap: 'wrap' }}>
              {plan.has_table_scan ? (
                <span 
                  style={{
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: '0.35rem',
                    padding: '3px 10px',
                    borderRadius: 'var(--radius-full)',
                    fontSize: '0.72rem',
                    fontWeight: 600,
                    fontFamily: 'var(--font-body)',
                    backgroundColor: 'var(--cohere-amber-bg)',
                    color: 'var(--cohere-amber-text)',
                    border: '1px solid var(--cohere-amber-border)',
                  }}
                  title="Query scans entire table rows sequentially. Consider adding an index for high-scale tables."
                >
                  <AlertCircle style={{ width: '0.75rem', height: '0.75rem' }} />
                  Full Table Scan Detected
                </span>
              ) : (
                <span 
                  style={{
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: '0.35rem',
                    padding: '3px 10px',
                    borderRadius: 'var(--radius-full)',
                    fontSize: '0.72rem',
                    fontWeight: 600,
                    fontFamily: 'var(--font-body)',
                    backgroundColor: 'var(--cohere-pale-green)',
                    color: 'var(--cohere-deep-green)',
                    border: '1px solid var(--cohere-success-border)',
                  }}
                >
                  <Check style={{ width: '0.75rem', height: '0.75rem' }} />
                  No Full Table Scans
                </span>
              )}

              {plan.has_index_lookup && (
                <span 
                  style={{
                    display: 'inline-flex',
                    alignItems: 'center',
                    gap: '0.35rem',
                    padding: '3px 10px',
                    borderRadius: 'var(--radius-full)',
                    fontSize: '0.72rem',
                    fontWeight: 600,
                    fontFamily: 'var(--font-body)',
                    backgroundColor: 'var(--cohere-pale-blue)',
                    color: 'var(--cohere-action-blue)',
                    border: '1px solid var(--cohere-hairline)',
                  }}
                  title="Query efficiently takes advantage of indexed keys or B-trees."
                >
                  <LayersThree01 style={{ width: '0.75rem', height: '0.75rem' }} />
                  Index / Key Search Used
                </span>
              )}
            </div>

            {/* Timing Metric & Navigation Tabs */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
              <div 
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '0.35rem',
                  fontFamily: 'var(--font-mono)',
                  fontSize: '0.72rem',
                  color: 'var(--cohere-muted)',
                }}
              >
                <Clock style={{ width: '0.8rem', height: '0.8rem' }} />
                <span>{plan.execution_time_ms} ms</span>
              </div>

              {/* Tab Selector */}
              <div 
                role="tablist"
                aria-label="Explain plan view modes"
                style={{
                  display: 'flex',
                  gap: '2px',
                  backgroundColor: 'var(--cohere-soft-stone)',
                  border: '1px solid var(--cohere-hairline)',
                  borderRadius: 'var(--radius-xl)',
                  padding: '2px',
                }}
              >
                {(['visual', 'raw', 'sql'] as const).map((tab) => (
                  <button
                    key={tab}
                    role="tab"
                    aria-selected={activeTab === tab}
                    onClick={() => setActiveTab(tab)}
                    style={{
                      padding: '3px 10px',
                      fontSize: '11px',
                      fontWeight: 600,
                      borderRadius: 'var(--radius-xl)',
                      border: 'none',
                      cursor: 'pointer',
                      fontFamily: 'var(--font-body)',
                      textTransform: 'capitalize',
                      backgroundColor: activeTab === tab ? 'var(--cohere-primary)' : 'transparent',
                      color: activeTab === tab ? 'var(--cohere-canvas)' : 'var(--cohere-muted)',
                      transition: 'all 0.15s ease',
                    }}
                  >
                    {tab === 'visual' ? 'Plan Steps' : tab === 'raw' ? 'Raw Output' : 'SQL'}
                  </button>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* Modal Body */}
        <div style={{ padding: '1.25rem', overflowY: 'auto', flex: 1, backgroundColor: 'var(--bg-card)' }}>
          {isLoading ? (
            <div 
              style={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                justifyContent: 'center',
                padding: '4rem 1rem',
                gap: '0.75rem',
              }}
            >
              <div 
                style={{
                  width: '2rem',
                  height: '2rem',
                  border: '3px solid var(--cohere-hairline)',
                  borderTopColor: 'var(--cohere-primary)',
                  borderRadius: '50%',
                  animation: 'spin 0.8s linear infinite',
                }} 
              />
              <p style={{ fontFamily: 'var(--font-body)', fontSize: '0.85rem', color: 'var(--cohere-muted)' }}>
                Analyzing query execution path with database engine...
              </p>
            </div>
          ) : plan?.error ? (
            <div 
              style={{
                padding: '1.25rem',
                borderRadius: 'var(--radius-sm)',
                backgroundColor: 'var(--cohere-error-bg)',
                border: '1px solid var(--cohere-error-border)',
                display: 'flex',
                alignItems: 'flex-start',
                gap: '0.75rem',
              }}
            >
              <AlertCircle style={{ width: '1.25rem', height: '1.25rem', color: 'var(--cohere-error)', flexShrink: 0, marginTop: '2px' }} />
              <div>
                <h4 style={{ fontFamily: 'var(--font-display)', fontSize: '0.9rem', fontWeight: 600, color: 'var(--cohere-error)', marginBottom: '0.25rem' }}>
                  Execution Plan Error
                </h4>
                <p style={{ fontFamily: 'var(--font-mono)', fontSize: '0.78rem', color: 'var(--cohere-error)', lineHeight: 1.5 }}>
                  {plan.error}
                </p>
              </div>
            </div>
          ) : !plan ? (
            <div style={{ textAlign: 'center', padding: '3rem 1rem', color: 'var(--cohere-muted)' }}>
              No execution plan available.
            </div>
          ) : (
            <>
              {/* Tab: Visual Plan Steps */}
              {activeTab === 'visual' && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                  <div 
                    style={{
                      border: '1px solid var(--cohere-hairline)',
                      borderRadius: 'var(--radius-sm)',
                      overflow: 'hidden',
                    }}
                  >
                    <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.78rem' }}>
                      <thead>
                        <tr style={{ backgroundColor: 'var(--cohere-soft-stone)', borderBottom: '1px solid var(--cohere-hairline)' }}>
                          <th style={{ padding: '0.6rem 0.85rem', textAlign: 'left', fontWeight: 700, fontFamily: 'var(--font-mono)', color: 'var(--cohere-ink)', width: '3.5rem' }}>Step</th>
                          <th style={{ padding: '0.6rem 0.85rem', textAlign: 'left', fontWeight: 700, fontFamily: 'var(--font-mono)', color: 'var(--cohere-ink)' }}>Operation / Access Strategy</th>
                          <th style={{ padding: '0.6rem 0.85rem', textAlign: 'left', fontWeight: 700, fontFamily: 'var(--font-mono)', color: 'var(--cohere-ink)', width: '8rem' }}>Type</th>
                        </tr>
                      </thead>
                      <tbody>
                        {plan.raw_plan.map((line, idx) => {
                          const isScan = line.toLowerCase().includes('scan');
                          const isSearch = line.toLowerCase().includes('search') || line.toLowerCase().includes('index');
                          const isTemp = line.toLowerCase().includes('temp') || line.toLowerCase().includes('b-tree');

                          let badgeLabel = 'Execution Node';
                          let badgeBg = 'var(--cohere-soft-stone)';
                          let badgeColor = 'var(--cohere-muted)';

                          if (isScan) {
                            badgeLabel = 'Table Scan';
                            badgeBg = 'var(--cohere-amber-bg)';
                            badgeColor = 'var(--cohere-amber-text)';
                          } else if (isSearch) {
                            badgeLabel = 'Index Search';
                            badgeBg = 'var(--cohere-pale-green)';
                            badgeColor = 'var(--cohere-deep-green)';
                          } else if (isTemp) {
                            badgeLabel = 'Temp Memory';
                            badgeBg = 'var(--cohere-purple-bg)';
                            badgeColor = 'var(--cohere-purple-text)';
                          }

                          return (
                            <tr 
                              key={idx} 
                              style={{ 
                                borderBottom: idx === plan.raw_plan.length - 1 ? 'none' : '1px solid var(--cohere-hairline)',
                                backgroundColor: idx % 2 === 1 ? 'var(--cohere-soft-stone)' : 'var(--bg-card)',
                              }}
                            >
                              <td style={{ padding: '0.6rem 0.85rem', fontFamily: 'var(--font-mono)', color: 'var(--cohere-muted)' }}>
                                #{idx + 1}
                              </td>
                              <td style={{ padding: '0.6rem 0.85rem', fontFamily: 'var(--font-mono)', color: 'var(--cohere-ink)', lineHeight: 1.5 }}>
                                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                                  <GitBranch style={{ width: '0.85rem', height: '0.85rem', color: 'var(--cohere-muted)', flexShrink: 0 }} />
                                  <span>{line}</span>
                                </div>
                              </td>
                              <td style={{ padding: '0.6rem 0.85rem' }}>
                                <span 
                                  style={{
                                    fontSize: '0.68rem',
                                    fontWeight: 600,
                                    fontFamily: 'var(--font-body)',
                                    padding: '2px 8px',
                                    borderRadius: 'var(--radius-xs)',
                                    backgroundColor: badgeBg,
                                    color: badgeColor,
                                    whiteSpace: 'nowrap',
                                  }}
                                >
                                  {badgeLabel}
                                </span>
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>

                  {/* Architecture explanation footer */}
                  <div 
                    style={{
                      padding: '0.75rem 1rem',
                      borderRadius: 'var(--radius-xs)',
                      backgroundColor: 'var(--cohere-soft-stone)',
                      border: '1px solid var(--cohere-hairline)',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '0.625rem',
                      fontSize: '0.74rem',
                      color: 'var(--cohere-body-muted)',
                      fontFamily: 'var(--font-body)',
                    }}
                  >
                    <Database01 style={{ width: '0.9rem', height: '0.9rem', color: 'var(--cohere-primary)', flexShrink: 0 }} />
                    <span>
                      Query execution plans reveal the low-level query optimizer route. Steps marked <strong>Index Search</strong> use primary or secondary indexes, whereas <strong>Table Scan</strong> traverses every row in storage.
                    </span>
                  </div>
                </div>
              )}

              {/* Tab: Raw Plan Output */}
              {activeTab === 'raw' && (
                <div style={{ position: 'relative' }}>
                  <button
                    onClick={handleCopyRaw}
                    className="btn-cohere-pill-outline"
                    style={{
                      position: 'absolute',
                      top: '0.75rem',
                      right: '0.75rem',
                      padding: '4px 10px',
                      fontSize: '11px',
                      backgroundColor: copied ? 'var(--cohere-pale-green)' : 'var(--bg-card)',
                      borderColor: copied ? 'var(--cohere-success)' : 'var(--cohere-hairline)',
                      color: copied ? 'var(--cohere-success)' : 'var(--cohere-ink)',
                      zIndex: 2,
                    }}
                  >
                    {copied ? (
                      <>
                        <Check style={{ width: '0.75rem', height: '0.75rem', color: 'var(--cohere-deep-green)' }} />
                        <span>Copied!</span>
                      </>
                    ) : (
                      <>
                        <Copy01 style={{ width: '0.75rem', height: '0.75rem' }} />
                        <span>Copy Output</span>
                      </>
                    )}
                  </button>

                  <pre 
                    style={{
                      backgroundColor: 'var(--cohere-dark-navy)',
                      color: '#f8fafc',
                      padding: '1.25rem',
                      borderRadius: 'var(--radius-sm)',
                      fontFamily: 'var(--font-mono)',
                      fontSize: '0.78rem',
                      lineHeight: 1.7,
                      overflowX: 'auto',
                      whiteSpace: 'pre-wrap',
                      margin: 0,
                    }}
                  >
                    {plan.raw_plan.join('\n')}
                  </pre>
                </div>
              )}

              {/* Tab: Underlying SQL */}
              {activeTab === 'sql' && (
                <div>
                  <div 
                    style={{
                      display: 'flex',
                      alignItems: 'center',
                      gap: '0.5rem',
                      marginBottom: '0.5rem',
                      fontFamily: 'var(--font-mono)',
                      fontSize: '0.72rem',
                      color: 'var(--cohere-muted)',
                    }}
                  >
                    <Terminal style={{ width: '0.8rem', height: '0.8rem' }} />
                    <span>TARGET SQL QUERY BEING EXPLAINED</span>
                  </div>
                  <div 
                    style={{
                      backgroundColor: 'var(--cohere-canvas)',
                      border: '1px solid var(--cohere-hairline)',
                      padding: '1rem',
                      borderRadius: 'var(--radius-sm)',
                      overflowX: 'auto',
                    }}
                  >
                    <div style={{ display: 'table', width: '100%', overflowX: 'auto' }}>
                      {highlightSql(plan.sql || sql, true)}
                    </div>
                  </div>
                </div>
              )}
            </>
          )}
        </div>

        {/* Modal Footer */}
        <div 
          style={{
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'flex-end',
            padding: '0.75rem 1.5rem',
            borderTop: '1px solid var(--cohere-hairline)',
            backgroundColor: 'var(--cohere-canvas)',
          }}
        >
          <button
            onClick={onClose}
            className="btn-cohere-primary"
            style={{ padding: '6px 18px', fontSize: '12px' }}
          >
            Done
          </button>
        </div>
      </div>
    </div>
  );
}
